{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cancerr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cancerR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cancerR/cancerR_{{ version }}.tar.gz
  sha256: 20caf9d40951b6cfcebdd8f92b2aaffb1f511bc6edd05936afb41753fe69640a

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('cancerR')"           # [not win]
    - "\"%R%\" -e \"library('cancerR')\""  # [win]

about:
  home: https://github.com/giancarlodigi/cancerR
  license: GPL-2.0-or-later
  summary: Classifies the type of cancer using routinely collected data commonly found in cancer
    registries from pathology reports. The package implements the International Classification
    of Diseases for Oncology, 3rd Edition site (topography), histology (morphology),
    and behaviour codes of neoplasms to classify cancer type <https://www.who.int/standards/classifications/other-classifications/international-classification-of-diseases-for-oncology>.
    Classification in children utilize the International Classification of Childhood
    Cancer by Steliarova-Foucher et al. (2005) <doi:10.1002/cncr.20910>. Adolescent
    and young adult cancer classification is based on Barr et al. (2020) <doi:10.1002/cncr.33041>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
# Type: Package

extra:
  recipe-maintainers:
    - conda-forge/r
    - giancarlodigi

# Package: cancerR
# Title: Classification of Cancer Using Administrative Data
# Version: 0.1.0
# Authors@R: c( person(given   = "Giancarlo", family  = "Di Giuseppe", role    = c("aut", "cre", "cph"), email   = "digi.giancarlo@proton.me", comment = c(ORCID = "0000-0001-5112-7560")))
# Description: Classifies the type of cancer using routinely collected data commonly found in cancer registries from pathology reports. The package implements the International Classification of Diseases for Oncology, 3rd Edition site (topography), histology (morphology), and behaviour codes of neoplasms to classify cancer type <https://www.who.int/standards/classifications/other-classifications/international-classification-of-diseases-for-oncology>. Classification in children utilize the International Classification of Childhood Cancer by Steliarova-Foucher et al. (2005) <doi:10.1002/cncr.20910>. Adolescent and young adult cancer classification is based on Barr et al. (2020) <doi:10.1002/cncr.33041>.
# License: GPL (>= 2)
# URL: https://github.com/giancarlodigi/cancerR
# BugReports: https://github.com/giancarlodigi/cancerR/issues
# Depends: R (>= 2.10)
# Suggests: knitr, rmarkdown, testthat (>= 3.0.0)
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# NeedsCompilation: no
# Packaged: 2024-09-11 21:13:25 UTC; giancarlo
# Author: Giancarlo Di Giuseppe [aut, cre, cph] (<https://orcid.org/0000-0001-5112-7560>)
# Maintainer: Giancarlo Di Giuseppe <digi.giancarlo@proton.me>
# Repository: CRAN
# Date/Publication: 2024-09-15 19:40:02 UTC
